検索結果画面の実装
2022-team-bulletin-board/2022-bulletin-board-application pull request #14
Opened 2022-03-14 00:51 UTC by tora87

検索結果画面のレイアウト
検索機能の実装

2022-03-14 01:45 UTC, youhei-takahashi commented on db/question.php
> +      group by q.question_id;";
検索対象は`question.question_title`のみで仕様と合っていますか？
`question.question_detail`は見なくても良いですか？
さらには`answer.answer_detail`まで見るという考え方もあると思います。

2022-03-14 01:51 UTC, youhei-takahashi commented on db/question.php
> +      group by q.question_id;";
SELECT で指定しているカラムはすべて GROUP BY でも指定しましょう。
今回使っているMySQLではたまたま動いていますが、これを許容しないDBMSもあります。

```suggestion
      //sql文作成
      $sql = "select q.question_id,question_title,question_detail,question_created,question_bestanswer,COUNT(ans.answer_id) as answer_count FROM question as q
      left outer join answer as ans on q.question_id = ans.question_id
      where q.question_title like :keyword
      group by q.question_id, question_title, question_detail, question_created, question_bestanswer;";
```

2022-03-14 01:53 UTC, youhei-takahashi commented
【参考までに】
一応、DBにデータを追加してここまで確認したので、スクリーンショットを残しておきます。
ローカルでもテストはしていると思いますが、網羅性を考慮したテストをするようにしましょう！
(もし、していなかった次からは気を付けましょう。)
![image](https://user-images.githubusercontent.com/50701460/158091394-e53e98c5-2236-49d4-b677-076184e01822.png)

2022-03-14 02:58 UTC, tora87 commented on db/question.php
> +      group by q.question_id;";
ありがとうございます、修正しました。
https://github.com/2022-team-bulletin-board/2022-bulletin-board-application/pull/14/commits/00ba1aec3f3bd88f5914ce7073f0c7fb4cd77be7

2022-03-14 02:58 UTC, tora87 commented on db/question.php
> +      group by q.question_id;";
話し合った結果、titleとdetailを検索対象にすることになりました。

https://github.com/2022-team-bulletin-board/2022-bulletin-board-application/pull/14/commits/00ba1aec3f3bd88f5914ce7073f0c7fb4cd77be7

2022-03-14 05:59 UTC, youhei-takahashi commented on db/question.php
> +      group by q.question_id;";
2点指摘です。
- 細かいですが、GROUP BY のカラムの方にも `q.` とつけましょう。
- SQL の演算子の優先順位(ANDとOR)について調べてみてください。

2022-03-15 04:40 UTC, tsushima3074 requested changes

2022-03-15 04:56 UTC, tora87 commented on header.php
> +          <input type="search" name="search_word" placeholder="検索したいワードを入力してください">
検索フォームに関しては「検索文字列がURLクエリパラメータに出てるイメージが自分の中であった」くらいの理由しかなく、特にこれといった理由はないです。
POSTが必須な部分でもないのかなと思いました。

2022-03-16 05:50 UTC, tora87 commented on db/question.php
> +      $stmt->bindValue(':keyword','%'.$search_word.'%', PDO::PARAM_STR);
https://github.com/2022-team-bulletin-board/2022-bulletin-board-application/pull/14/commits/b0fb0c12a8a14ec84ccd2fc62956a305a1e19615
ありがとうございます、修正しました。

2022-03-16 05:51 UTC, tora87 commented on searchQuestion.php
> +  if (isset($_GET["search_word"]) && $_GET["search_word"] !== "" ) {
https://github.com/2022-team-bulletin-board/2022-bulletin-board-application/pull/14/commits/cd92da12b09db83b27031fa1f54011000be71749
実装しました。

2022-03-16 05:52 UTC, tora87 commented on searchQuestion.php
> +        <div class="search-result-text"><?php echo "「${keyword}」"?>の検索結果：<?php echo $size > 0 ? $size.'件ヒットしました。' : '見つかりませんでした。'?></div>
https://github.com/2022-team-bulletin-board/2022-bulletin-board-application/pull/14/commits/343b9aa00d8a41bff35d8922de76ea0d047c5f30

おっしゃる通りだと思います。
修正しました。

2022-03-16 05:52 UTC, tora87 commented on db/question.php
> +      left outer join answer as ans on q.question_id = ans.question_id
https://github.com/2022-team-bulletin-board/2022-bulletin-board-application/pull/14/commits/79066a551db813ff1feddd472ba852500a32c7b0
実装しました。

2022-03-16 06:05 UTC, youhei-takahashi commented
@tora87 
検索画面の一覧のリンクを本物に修正をしてください！
(Mergeしたら動くように)

ちなみにこうゆう場合は`#`にしておくのではなく、遷移先のphpファイルのスタブを用意してパラメータも渡して動くような状態でPRを作る方が良いです。
そうすると、遷移先が実装されたときにこちらのファイルをそれに合わせて修正する必要がなくなります。

2022-03-16 06:27 UTC, youhei-takahashi approved these changes
確認しました。

@tsushima3074 
津嶋君の指摘の部分は見てないので、お任せします！

2022-03-17 00:34 UTC, tsushima3074 approved these changes

2022-03-17 00:35 UTC, merged